### ISSUE TITLE
LREM command argument order

### ISSUE THREAD

**Issue by schoeppi5** [alphazero/Go-Redis#34]
The LREM command of Redis server in version 5.0.3 expects three arguments in the order `key` `count` `value`. See the [docs](https://redis.io/commands/lrem) for more information.

Currently, the commend seems to be implemented with the arguments in the wrong order (`key` `value` `count`) and therefore does not work.

For replication of this problem try the following code:
```Go
package main

import (
	"github.com/alphazero/go-redis"
)

func main() {
	spec := redis.DefaultSpec().Host(redis.DefaultRedisHost).Port(redis.DefaultRedisPort).Password(redis.DefaultRedisPassword).Db(1)
	client, err := redis.NewSynchClientWithSpec(spec)
	if err != nil {
		return
	}

	defer client.Quit()

	client.Lpush("test", []byte("Test"))
	client.Lpush("test", []byte("Test"))
	client.Lpush("test", []byte("Test"))

	removedItems, err := client.Lrem("test", []byte("test"), 0) // current implementation
	// removedItems, err := client.Lrem("test", 0, []byte("test")) // Should be implemented like this
	if err != nil {
		println(err)
	}
}
```

Thanks in advance for your help with this problem!
schoeppi5

**Comment by alphazero** [comment]
See the [version_compliance](https://github.com/alphazero/Go-Redis/blob/go1/compliance_note.txt) in project root. I would think quite a few things have changed since `2.4.9`.

Changing a single command to conform to a later version doesn't make sense. 

If you need the fix for your own personal use, I suggest just swapping the argument order for that specific command.  

Thank you for reporting.
