### ISSUE TITLE
not usable with go get

### ISSUE THREAD

**Issue by bpowers** [alphazero/Go-Redis#7]
I know this project has a lot of followers, it would be great if it could be installed with go get.  The best way to do this is probably by renaming the repository to 'redis'.  I did this here:
https://github.com/bpowers/redis
For my own personal use.

Thoughts?

**Comment by alphazero** [comment]
Clearly it is a simple matter to just change the repo name.  I did consider it long ago, and having reflected on various ramifications.  

It offends my sensibilities as an engineer, Bobby, to make un-necessary changes that would impact existing user code due to the requirements of a half-baked tool:  
- Conflating location and identity is not quite thoughtful (being very generous with the choice of words here).  
- Insisting that all repositories contain a single top level package is also limiting and equally not well thought through.  
- As it was pointed out elsewhere, versioning is another issue that would need to be addressed. 
- @antirez Redis has numerous active branches and client libraries may need to reflect branch structure to maintain compatible versions.  Which branch will go get pull?

Conclusions:

I use various Go packages, for example @feyeleanor excellent work, without once using the go get mechanism or having the slightest discomfort or issues.  The notion of import "http://github.com/alphazero/redis" creates deeper problems than the non-issue that it purportedly solves -- the claimed utility boils down to a 'neat pet trick' for the dog and pony show of blog posts and conference circuit/circus.  It is of no use in production and would certainly not pass substantial code reviews conducted by yours truly.

Cheers.

**Comment by bpowers** [comment]
I'll take that as a 'no' :)

**Comment by alphazero** [comment]
))) Yes, Bobby.  Think of it as my version of Go's stringent compiler.  
You'll thank me when you are on L3 support call.
